-- Read-only fingerprint for customer debts.
SELECT
  (SELECT MAX(dt) FROM (
      SELECT MAX(S_DATE) AS dt FROM dbo.SALE_INVOICE WHERE ISNULL(S_STATUES, 1) NOT IN (0, 2)
      UNION ALL SELECT MAX(T_DATE) FROM dbo.TAKE WHERE ISNULL(T_STATUES, 1) <> 2
      UNION ALL SELECT MAX(G_DATE) FROM dbo.GIVE WHERE ISNULL(G_STATUES, 1) <> 2
      UNION ALL SELECT MAX(BL_DATE) FROM dbo.BALANCE_EDIT WHERE ISNULL(BL_STATUES, 1) <> 2
      UNION ALL SELECT MAX(S_R_DATE) FROM dbo.S_R_INVOICE_VIEW WHERE ISNULL(S_R_STATUES, 1) NOT IN (0, 2)
  ) x) AS max_activity,
  (SELECT COUNT(*) FROM dbo.TAKE WHERE ISNULL(T_STATUES, 1) <> 2) AS take_rows,
  (SELECT COUNT(*) FROM dbo.GIVE WHERE ISNULL(G_STATUES, 1) <> 2) AS give_rows,
  (SELECT COUNT(*) FROM dbo.SALE_INVOICE WHERE ISNULL(S_STATUES, 1) NOT IN (0, 2)) AS sale_rows;
