-- Read-only fingerprint for supplier debts.
SELECT
  (SELECT MAX(B_DATE) FROM dbo.BUY_ITEMS_INVOICE_VIEW WHERE ISNULL(B_STATUES, 1) NOT IN (0, 2)) AS max_buy,
  (SELECT MAX(T_DATE) FROM dbo.TAKE_VIEW WHERE ISNULL(T_STATUES, 1) NOT IN (0, 2)) AS max_take,
  (SELECT MAX(G_DATE) FROM dbo.GIVE_VIEW WHERE ISNULL(G_STATUES, 1) NOT IN (0, 2)) AS max_give,
  (SELECT COUNT(*) FROM dbo.CUSTOMERS WHERE CUST_VENDOR = 1) AS vendor_count,
  (SELECT CHECKSUM_AGG(CHECKSUM(CUST_ID)) FROM dbo.CUSTOMERS WHERE CUST_VENDOR = 1) AS vendor_id_ck;
