-- Read-only fingerprint for shortages / required-items drivers.
SELECT
  (SELECT CHECKSUM_AGG(CHECKSUM(ITEM_ID, CAST(ISNULL(QTY, 0) * 10000 AS BIGINT)))
   FROM dbo.ITEMS_SUB WHERE ITEM_ID IS NOT NULL) AS stock_ck,
  (SELECT CHECKSUM_AGG(CHECKSUM(ITEM_ID, CAST(ISNULL(MIN_LEVEL, 0) * 100 AS INT), CAST(ISNULL(MAX_LEVEL, 0) * 100 AS INT)))
   FROM dbo.ITEMS WHERE ISNULL(ITEM_INVISIBLE, 0) = 0) AS level_ck,
  (SELECT MAX(si.S_TIME)
   FROM dbo.SALE_ITEMS si
   INNER JOIN dbo.SALE_INVOICE sh ON sh.S_ID = si.S_ID
   WHERE si.S_TIME >= DATEADD(day, -30, GETDATE())
     AND ISNULL(sh.S_STATUES, 1) = 1
     AND ISNULL(si.QTY, 0) > 0) AS max_sale_30d,
  (SELECT MAX(B_DATE)
   FROM dbo.BUY_INVOICE
   WHERE ISNULL(B_STATUES, 1) NOT IN (0, 2)
     AND B_DATE >= DATEADD(day, -365, GETDATE())) AS max_buy_365d;
